#! /bin/sh
#
# pre-inst-env gnucobol
#
# Copyright (C) 2017,2019-2020 Free Software Foundation, Inc.
# Written by Mathieu Lirzin, Simon Sobisch, 
#
# This file is part of GnuCOBOL.
#
# The GnuCOBOL compiler is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# GnuCOBOL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuCOBOL.  If not, see <https://www.gnu.org/licenses/>.

PATH="/home/christoph/cob/gnucobol-3.1-rc1/libcob/.libs:${PATH}"
PATH="/home/christoph/cob/gnucobol-3.1-rc1/cobc:/home/christoph/cob/gnucobol-3.1-rc1/bin:${PATH}"
export PATH


# trigger the preference of local instead of installed files
#GNUCOBOL_UNINSTALLED=1
#export GNUCOBOL_UNINSTALLED

# let atlocal know that there's less to setup
GNUCOBOL_ENV_SETUP=1
export GNUCOBOL_ENV_SETUP

exec_prefix="/usr/local" # this is is likely referenced in the LIBS entries below

# options that are also used in atlocal (always add to both)
COB_CFLAGS="-I/home/christoph/cob/gnucobol-3.1-rc1 -I/usr/local/include -Wno-unused -fsigned-char -Wno-pointer-sign -Qunused-arguments -I/home/christoph/COBOL/bitcode-managed/include -pipe"
COB_LDFLAGS="-L/home/christoph/COBOL/bitcode-managed/lib"
COB_LIBS="-L/home/christoph/cob/gnucobol-3.1-rc1/libcob/.libs -L${exec_prefix}/lib -lcob -lm"
COB_CONFIG_DIR="/home/christoph/cob/gnucobol-3.1-rc1/config"
COB_COPY_DIR="/home/christoph/cob/gnucobol-3.1-rc1/copy"
LD_LIBRARY_PATH="/home/christoph/cob/gnucobol-3.1-rc1/libcob/.libs:${LD_LIBRARY_PATH}"     # GNU/Linux, Solaris, ...
DYLD_LIBRARY_PATH="/home/christoph/cob/gnucobol-3.1-rc1/libcob/.libs:{$DYLD_LIBRARY_PATH}" # Mac OS
SHLIB_PATH="/home/christoph/cob/gnucobol-3.1-rc1/libcob/.libs:${SHLIB_PATH}"               # HP-UX
LIBPATH="/home/christoph/cob/gnucobol-3.1-rc1/libcob/.libs:${LIBPATH}"                     # AIX
COB_LIBRARY_PATH="/home/christoph/cob/gnucobol-3.1-rc1/extras:${COB_LIBRARY_PATH}"         # only in pre-inst case: prepend

export COB_CFLAGS COB_LDFLAGS COB_LIBS
export COB_CONFIG_DIR COB_COPY_DIR
export LD_LIBRARY_PATH DYLD_LIBRARY_PATH SHLIB_PATH LIBPATH
export COB_LIBRARY_PATH

# not robust check, but better than none
if test "x${BASH_SOURCE}" != "x" -a "${BASH_SOURCE}" != "$0"; then
	echo "This script should not be sourced but called instead!"
else
	if test "x$1" != "x"; then
		exec "$@"
	else
		$SHELL
	fi
fi

